- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  - Bagel
  - Barratry
  - Box
  - Cluster
  - Core
  - Fland
  - Gemini
  - Marathon
  - Meta
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
  - Falcon
 # - RadStation
 # - EstacaoPirata
